
spring.datasource.url=jdbc:postgresql://localhost:5432/projetourbano
spring.datasource.username=postgres
spring.datasource.password=FlinneEllie

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect